- src/pages/index.js
Update the description metadata.
> Update the description metadata

- .github/pull_request_template.md
- i18n/zh/docusaurus-plugin-content-docs/current.json
- Update a sidebar entry for i18N error.
- Refine the markdown format of PR template.
Here are some reminders before you submit the pull request:
* Make sure your Pull Request has a clear title and commit message
* Please sign the Contributor License Agreement as promoted for your
first-time contribution
* Make sure your changes deployment preview is successful
Issues](https://github.com/cloudberrydb/cloudberrydb-site/issues) or
[Discussions](https://github.com/orgs/cloudberrydb/discussions) (if
has or needed)
* Feel free to ask for @doc team or other people to help review and
approve
> docs: fix a sidebar zh i18n error

- .github/pull_request_template.md
- src/pages/index.js
---
Update the meta information for the Cloudberry Database website, and update the pull request template for contributors.
* Make sure that your Pull Request has a clear title and commit message.
* Sign the Contributor License Agreement as prompted for your first-time contribution.
* List your communications in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb-site/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
* Feel free to ask for the @doc team or other people to help review and approve.
> Website: update the title and description

- docusaurus.config.js
- package.json
---
Add Google Analytics to the site …
> Add Google Analytics to the site

- blog/2023-10-13-sep-monthly.md
---
Add Sep monthly newsletter post. …
> Add Sep monthly newsletter

- blog/2023-09-05-august-monthly.md
- blog/2023-10-13-sep-monthly.md
- blog/2023-11-01-oct-monthly.md
---
Add Oct newsletter for CloudberryDB …
> Add Oct newsletter for CloudberryDB

- blog/2023-12-29-dec-monthly.md
---
Add Dec monthly newsletter. …
> Add Dec monthly newsletter

- blog/2023-09-05-august-monthly.md
- blog/2023-10-13-sep-monthly.md
- blog/2023-11-01-oct-monthly.md
- blog/2023-11-14-introducing-cloudberrydb-bootcamp.md
- blog/2023-12-01-nov-monthly.md
- blog/2023-12-29-dec-monthly.md
---
Add truncate marker to blogs. …
> Add truncate marker to blogs

- src/components/bootcamp/MainContent/CardLine.tsx
- src/components/bootcamp/MainContent/index.tsx
- src/components/common/Breadcrumbs/index.tsx
> style: bootcamp item margin

- src/consts/bootcampData.tsx
> fix: add cloudberrydb/bootcamp link

- src/components/home/HCard/index.tsx
- src/components/home/HCard/styles.module.scss
> fix: mobile locale bug

- docusaurus.config.ts
- src/components/common/Breadcrumbs/index.tsx
- src/components/contribute/Card/styles.module.scss
- src/components/home/HCard/index.tsx
- src/components/home/JoinCommunity/styles.module.scss
- src/css/custom.scss
- src/css/design-style.scss
> fix: refresh bug

- docusaurus.config.ts
---
Display the last update time and author info. …
> Add doc author info

- docs/releases/index.md
- docs/releases/release-1.5.0.md
- docusaurus.config.ts
- sidebars.ts
- src/css/design-style.scss
- src/theme/DocBreadcrumbs/Items/Home/index.tsx
- src/theme/DocBreadcrumbs/Items/Home/styles.module.css
- src/theme/DocBreadcrumbs/index.tsx
- src/theme/DocBreadcrumbs/styles.module.css
> feat: add algolia

- docusaurus.config.ts
> fix: change apiKey

- docusaurus.config.ts
> fix: algolia search

- .github/workflows/feishu-notify.yml
---
Add feishu-notify workflow …
> Add feishu-notify workflow

- docs/releases/release-1.5.1.md
- i18n/zh/docusaurus-plugin-content-docs/current/releases/release-1.5.1.md
- sidebars.ts
doc: add v1.5.1 release notes
--- …
> doc: add v1.5.1 release notes

- i18n/zh/docusaurus-theme-classic/navbar.json
---
Update Navbar translation. …
> Update Navbar translation

- i18n/zh/docusaurus-plugin-content-pages/bootcamp/cbdb-sandbox.md
- src/pages/bootcamp/cbdb-sandbox.md
---
Update CloudberryDB version in Sandbox. …
> Update CloudberryDB version in Sandbox

- docs/releases/release-1.5.2.md
- i18n/zh/docusaurus-plugin-content-docs/current/releases/release-1.5.2.md
- sidebars.ts
docs: add 1.5.2 release notes
--- …
> docs: add 1.5.2 release notes

- blog/2024-01-12-postgresql-technical-insights-1.md
- src/theme/BlogPostItem/index.tsx
> feat: chinese hidden

- i18n/zh/docusaurus-plugin-content-pages/bootcamp/cbdb-sandbox.md
- i18n/zh/docusaurus-plugin-content-pages/contribute/code.md
- i18n/zh/docusaurus-plugin-content-pages/contribute/doc.md
- i18n/zh/docusaurus-plugin-content-pages/contribute/git.md
- i18n/zh/docusaurus-plugin-content-pages/contribute/how-to-contribute.md
- i18n/zh/docusaurus-plugin-content-pages/contribute/proposal.md
- src/consts/contribute.tsx
---
Add i18n-zh pages for contribute module. …
> Add i18n-zh pages for contribute module

- src/consts/support.tsx
---
Add i18n-zh for Support page. …
> Add i18n-zh for Support page

- src/consts/support.tsx
- src/css/pages/support.module.scss
- src/pages/support.tsx
> feat: add desc

- docs/releases/release-1.5.3.md
- i18n/zh/docusaurus-plugin-content-docs/current/releases/release-1.5.3.md
- sidebars.ts
---
Add 1.5.3 release notes
* List your communications in the …
> add 1.5.3 release notes

- src/pages/contribute/code.md
- src/pages/contribute/proposal.md
---
Made small fixes in the proposal and contribution guide docs.
* Make sure that your changes deployment preview is …
> small fixes to proposal and contribution docs

- docs/cbdb-op-prepare-to-deploy.md
- docs/deploy-cbdb-with-single-node.md
- i18n/zh/docusaurus-plugin-content-docs/current/cbdb-op-prepare-to-deploy.md
- i18n/zh/docusaurus-plugin-content-docs/current/deploy-cbdb-with-single-node.md
---
Corrected description of the `vm.overcommit_memory` parameter.
* Make sure that your changes deployment preview is …
> Fix overcommit memory desc

- docs/configure-row-level-security-policy.md
- i18n/zh/docusaurus-plugin-content-docs/current/configure-row-level-security-policy.md
- sidebars.ts
---
Added the RSL policy topic in both EN and CH.
* List your …
> added rsl policy topic

- docs/cbdb-linux-compile.md
- i18n/zh/docusaurus-plugin-content-docs/current/cbdb-linux-compile.md
closes: #143
---
update zh docs
> docs: fix zh el8 compile docs bug for CBDB

- docs/sys-utilities/pg-filedump.md
- i18n/zh/docusaurus-plugin-content-docs/current/sys-utilities/pg-filedump.md
- sidebars.ts
docs: add filedump docs
ref: https://github.com/cloudberrydb/filedump
---
* List your …
> docs: add filedump docs

- src/css/design-style.scss
- src/theme/Navbar/Layout/index.tsx
> fix: doc folding issue

- docs/sys-admin/backup-and-restore/index.md
Create, alter, drop, .. are DDL operations
closes: #165
---
Create, alter, drop, .. are DDL operations.
> DML -> DDL

- .asf.yaml
- .github/workflows/publish-cloudberry-site.yml
---
Add GitHub Actions for site. …
> Add GitHub Actions for site

- .asf.yaml
- .github/workflows/publish-cloudberry-site.yml
---
Fix deploy permissions and add asf-site branch protection.
Permission errors:
```
> Push the commit or tag
/usr/bin/git push origin asf-site
remote: Permission to apache/cloudberry-site.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/apache/cloudberry-site.git/': The requested URL returned error: 403
Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```
* Sign the Contributor License Agreement as prompted for your first-time contribution (*One-time …
> Fix deploy permissions and add asf-site branch protection

- src/theme/BlogLayout/styles.module.scss
- src/theme/BlogPostItem/Container/index.tsx
- src/theme/BlogPostItem/index.tsx
- src/theme/DocRoot/Layout/styles.module.scss
- src/theme/Footer/styles.module.scss
> fix: optimization of mobile blog style

- src/consts/community.tsx
- src/pages/community/mailing-lists.md
closes: #198 
---
This pr includes two commits:
- Add a `mailing list` page to show the community members how to subscribe and unsubscribe to the mailing lists.
- Add the LinkedIn handle to the Community page. …
> Add mailing list page to the community module

- docusaurus.config.ts
- src/consts/community.tsx
- src/consts/support.tsx
- src/pages/community/security.md
- src/pages/contribute/how-to-contribute.md
---
As the ASF site checks[1], the "Security" should link to either to a project-specifi page, or to the main http://www.apache.org/security page.
[1] https://whimsy.apache.org/pods/project/cloudberry …
> Add new security page and update related links

- .github/workflows/publish-cloudberry-site.yml
---
Revert changes for asf-staging in the `.github/workflows/publish-cloudberry-site.yml` file.
* List your communications in the [GitHub Issues](https://github.com/apache/cloudberry-site/issues) or [Discussions](https://github.com/apache/cloudberry/discussions) (if has or needed). …
> Revert changes for asf-staging

- docusaurus.config.ts
- package-lock.json
- package.json
closes: #202 
---
As the ASF website checks and the privacy policy, we're not encouraged to use Google Analytics for our website. So change it to Matomo.
Also, delete the unused Google Anlytics-related modules from the pacakge list. …
> Change Google Analytics to Apache Matomo instance

- docs/advanced-analytics/pgvector-search.md
- sidebars.ts
Add pgvector doc to describe how to use pgvector search in cloudberry.
--- …
> Add pgvector doc

- src/pages/community/mailing-lists.md
---
Add a mailing list overview table for users to subscribe and subscribe to the mailing lists.
* List your communications in the [GitHub Issues](https://github.com/apache/cloudberry-site/issues) or [Discussions](https://github.com/apache/cloudberry/discussions) (if has or needed). …
> Add mailing list overview table

- src/pages/team.md
---
Add a committer module to show the committers' role and how to become one committer.
* List your communications in the [GitHub Issues](https://github.com/apache/cloudberry-site/issues) or [Discussions](https://github.com/apache/cloudberry/discussions) (if has or needed).
* Feel …
> Add committers module to team page

- docs/cbdb-rockylinux8-ubuntu-compile.md
- docs/cbdb-rockylinux9-compile.md
- docs/releases/release-1.5.3.md
- i18n/zh/docusaurus-plugin-content-docs/current/cbdb-linux-compile.md
- i18n/zh/docusaurus-plugin-content-docs/current/cbdb-rockylinux8-ubuntu-compile.md
- i18n/zh/docusaurus-plugin-content-docs/current/cbdb-rockylinux9-compile.md
- i18n/zh/docusaurus-plugin-content-docs/current/releases/release-1.5.3.md
- sidebars.ts
- src/consts/homeContent.tsx
docs: update cloudberry compile docs
- Remove CentOS 7 content from the build docs
- Add Rocky Linux 9 build guide based on https://github.com/edespino/cloudberry/blob/rocky9-dev-readme/deploy/build/README-rockylinux9.md and my test.
- Rename doc files to suit content changes
- Rename Cloudberry Database to Apache Cloudberry in build docs.
- Test the Rocky Linux 8 build guide and update content
---
* Learn the [code …
> docs: update cloudberry compile docs

- docs/performance/use-dynamic-tables.md
- i18n/zh/docusaurus-plugin-content-docs/current/performance/use-dynamic-tables.md
- sidebars.ts
> add dynamic table doc

- docusaurus.config.ts
- src/consts/homeContent.tsx
> Update Roadmap links

- src/pages/team/index.md
> Team page: Update PPMC members' org info and add new committers

- docs/deployment/configure.md
- docs/deployment/quick-build.md
- versioned_docs/version-2.x/deployment/configure.md
- versioned_docs/version-2.x/deployment/quick-build.md
> Fix the uncorrect user:group format

- docs/ecosystem/data-integration/seatunnel.md
- sidebars.ts
- versioned_docs/version-2.x/ecosystem/data-integration/seatunnel.md
- versioned_sidebars/version-2.x-sidebars.json
closes: #264 
---
* List your communications in the [GitHub Issues](https://github.com/apache/cloudberry-site/issues) or [Discussions](https://github.com/apache/cloudberry/discussions) (if …
> Add Apache SeaTunnel to Ecosystem

- docs/advanced-analytics/directory-tables.md
- docs/operate-with-data/pax-table-format.md
- i18n/zh/docusaurus-plugin-content-docs/current/advanced-analytics/directory-tables.md
- i18n/zh/docusaurus-plugin-content-docs/current/operate-with-data/pax-table-format.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.x/advanced-analytics/directory-tables.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.x/operate-with-data/pax-table-format.md
- versioned_docs/version-2.x/advanced-analytics/directory-tables.md
- versioned_docs/version-2.x/operate-with-data/pax-table-format.md
docs: revise docs according to feedback:
- remove a misleading note from the PAX doc
- add a note in directory table doc to clarify a limit
--- …
> docs: revise docs according to feedback

- .asf.yaml
> .asf.yaml: update PR settings

- src/pages/team/index.md
> Team: update PPMC and committer info

- docusaurus.config.ts
- src/components/home/MeetTheCommunity/index.module.scss
- src/components/home/SlackWechatTwitterYoutube/index.module.scss
- src/css/design-style.scss
- src/theme/Navbar/Content/styles.module.css
> Update docs label in the navbar
